name: Deploy ngmkt FE App

on:
  push:
    branches:
      - main  # Run this workflow when changes are pushed to the main branch

jobs:
  build-and-deploy:
    name: Build and Deploy Vue.js App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # - subdomain: "edzain"
          #   folder: "business_sites/edzain"
          # - subdomain: "bingoml"
          #   folder: "business_sites/bingoml"
          # - subdomain: "aromaperk"
          #   folder: "business_sites/aromaperk"
          # - subdomain: "phlorah"
          #   folder: "business_sites/phlorah"
          # - subdomain: "fitandfeet"
          #   folder: "business_sites/fitandfeet"
          # - subdomain: "totech"
          #   folder: "business_sites/totech"
          # - subdomain: "chosenconcept"
          #   folder: "business_sites/chosenconcept"
          # - subdomain: "amasemporium"
          #   folder: "business_sites/amasemporium"
          # - subdomain: "jomarsgroups"
          #   folder: "business_sites/jomarsgroups"
          # - subdomain: "royalrelish"
          #   folder: "business_sites/royalrelish"
          # - subdomain: "osasumwenbyfd"
          #   folder: "business_sites/osasumwenbyfd"
          # - subdomain: "hairarena"
          #   folder: "business_sites/hairarena"
          # - subdomain: "standardchoice"
          #   folder: "business_sites/standardchoice"
          # - subdomain: "standardchoice"
          # - subdomain: "ugbommaintefarms"
          #   folder: "business_sites/ugbommaintefarms"
          # - subdomain: "dreambarbers"
          #   folder: "business_sites/dreambarbers"
          # - subdomain: "jtsforte"
          #   folder: "business_sites/jtsforte"
          - subdomain: "24hrs"
            folder: "business_sites/24hrs"
          - subdomain: "flexglobalprime"
            folder: "business_sites/flexglobalprime"
          - subdomain: "munchiesevents"
            folder: "business_sites/munchiesevents"
          - subdomain: "dami"
            folder: "business_sites/dami"
          - subdomain: "crestgrandeur"
            folder: "business_sites/crestgrandeur"
          - subdomain: "lola"
            folder: "business_sites/lola"
          - subdomain: "mammanativekichen"
            folder: "business_sites/mammanativekichen"
          - subdomain: "alec"
            folder: "business_sites/alec"
            
            

      fail-fast: false  # Continue if one matrix job fails

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Full Git History
        run: |
          # Fetch the full history to ensure the before commit is available
          git fetch --unshallow
          git fetch origin ${{ github.ref }}  # Fetch the specific branch (in case it's shallow)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.18.1'

      # Step 4: Replace baseURL in Api.js
      - name: Replace baseURL in Api.js
        run: |
          echo "Updating API URL for subdomain: ${{ matrix.subdomain }}"
          case "${{ matrix.subdomain }}" in

            "24hrs")
              API_URL="https://api.24hrs.ngmkt.site"
              ;;
            "flexglobalprime")
              API_URL="https://api.flexglobalprime.ngmkt.site"
              ;;
            "munchiesevents")
              API_URL="https://api.munchiesevents.ngmkt.site"
              ;;
            "dami")
              API_URL="https://api.dami.ngmkt.site"
              ;;
            "crestgrandeur")
              API_URL="https://api.crestgrandeur.ngmkt.site"
              ;;
            "lola")
              API_URL="https://api.lola.ngmkt.site"
              ;;
            "mammanativekichen")
              API_URL="https://api.mammanativekichen.ngmkt.site"
              ;;
            "alec")
              API_URL="https://api.alec.ngmkt.site"
              ;;
            *)
              echo "Unknown subdomain!"
              exit 1
              ;;
          esac
          # Replace the base URL in Api.js file
          sed -i "s|http://localhost:9009/api/v1|$API_URL/api/v1|" ./src/javascript/Api/Api.js

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 6: Build the Vue.js app
      - name: Build Application
        run: npm run build

      # Step 7: Upload Built Files via SCP
      - name: Upload Built Files via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22  # SCP over SSH
          source: dist  # Local directory to upload
          target: ${{ secrets.FTP_PATH }}/${{ matrix.folder }}/frontend/  # Remote directory based on subdomain

      # Step 8: Run Post-Deployment Commands
      - name: Run Post-Deployment Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22  # SSH port
          script: |
            # Check and print the current working directory
            echo "Current working directory: $(pwd)"
            
            # Navigate to the target directory based on the subdomain
            cd "www/${{ matrix.folder }}/frontend" || { echo "Target directory does not exist"; exit 1; }

            # Verify that we are in the correct directory
            echo "Changed to directory: $(pwd)"

            # List the files in the directory for debugging purposes
            echo "Files in the current directory:"
            ls -la || { echo "Error: Failed to list files"; exit 1; }

            # Check if the dist folder exists before proceeding
            if [ -d dist ]; then
              # Change into the dist folder
              cd dist || { echo "Error: Failed to enter dist directory"; exit 1; }

              # Copy the built files to the parent directory
              cp -r * ../ || { echo "Error: Failed to copy files"; exit 1; }

              # Return to the public directory
              cd .. || { echo "Error: Failed to return to public directory"; exit 1; }

              # Remove the dist folder
              rm -rf dist || { echo "Error: Failed to remove dist folder"; exit 1; }
            else
              echo "Error: dist folder does not exist in $(pwd); exiting to avoid unintended deletion."
              exit 1
            fi
